apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrm-server
spec:
  selector:
    matchLabels:
      app: hrm-server
  template:
    metadata:
      labels:
        app: hrm-server
    spec:   
      containers:
      - name: hrm-server
        image: sooraj2022/hrm-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5002


